#!/bin/bash

echo "=== PHASE 2: LAUNCHING PLIP ON STABLE COMPLEXES ==="

# Check if the input directory from Phase 1 exists
if [ ! -d "complexes_pdb" ]; then
    echo "ERROR: The 'complexes_pdb' directory does not exist. Run Script 1 first."
    exit 1
fi

mkdir -p plip_reports

# Iterate directly over the generated PDB complex files
for complex_file in complexes_pdb/complex_*.pdb; do
    if [ -f "$complex_file" ]; then
        # Extract the base name (e.g., complex_ligand_name)
        base_name=$(basename "$complex_file" .pdb)
        ligand=${base_name#complex_}
        
        echo "----------------------------------------"
        echo "PLIP analyzing: $ligand"
        
        # Run PLIP natively and independently
        # Using -t (text report) and -y (PyMOL session)
        # Absolute path replaced with relative './plip_reports/' for portability
        plip -f "$complex_file" -t -y -o ./plip_reports/
        
        # Rename and index output results dynamically
        if [ -f "./plip_reports/report.txt" ]; then
            mv ./plip_reports/report.txt "./plip_reports/${ligand}_report.txt"
        fi
        
        if [ -f "./plip_reports/${base_name}.pse" ]; then
            mv "./plip_reports/${base_name}.pse" "./plip_reports/${ligand}_session.pse"
        fi
    fi
done

# Clean up temporary structural files generated by PLIP in the root directory
rm -f plipfixed.*

echo "=== PHASE 2 COMPLETE: Reports ready in 'plip_reports' ==="
